Скелет и дизайн проекта
alkurbatov/goph-keeper pull request #1
Opened 2023-05-02 15:01 UTC by alkurbatov

2023-05-03 15:23 UTC, alkurbatov commented
Добавил больше деталей по генерации ключа и аутентификации.

2023-05-07 16:09 UTC, kilchik requested changes
Структура проекта выглядит очень продуманной!
Отличный graceful shutdown!
Что будет, если клиентов будет несколько? Смогут ли они расшифровать секреты, созданные другим клиентом?
Клиент сможет запросить секрет по имени или только зная его uuid?

2023-05-07 16:09 UTC, kilchik commented on internal/keeper/app/app.go
> +		log.Fatal().Err(err).Msg("app - Run - logger.New")
Тут log будет nil

2023-05-07 16:09 UTC, kilchik commented on internal/keeper/app/app.go
> +		log.Fatal().Err(err).Msg("app - Run - postgres.New")
Использование log.Fatal лучше оставить исключительно в main. Это нормально использовать log.Fatal и аварийно завершать программу, если какие-то необходимые компоненты не удалось инициализировать при старте, но хочется максимально быстро понимать, откуда произошел такой вызов. Тут можно пробросить наверх ошибку

2023-05-07 16:09 UTC, kilchik commented on internal/keepctl/repo/users_keeper.go
> +package repo
А зачем клиенту UsersRepo?

2023-05-07 16:38 UTC, alkurbatov commented on internal/keeper/app/app.go
> +		log.Fatal().Err(err).Msg("app - Run - logger.New")
И правда, спасибо :)

2023-05-07 16:39 UTC, alkurbatov commented on internal/keepctl/repo/users_keeper.go
> +package repo
Исключительно для регистрации, новый клиент регистрирует сам себя командой `keepctl --username abc --pasword xxx register`.

2023-05-07 16:40 UTC, alkurbatov commented on internal/keeper/app/app.go
> +		log.Fatal().Err(err).Msg("app - Run - postgres.New")
Спасибо, да, так удобнее будет.

2023-05-07 16:44 UTC, alkurbatov commented
> Что будет, если клиентов будет несколько? Смогут ли они расшифровать секреты, созданные другим клиентом? 

Здесь я планирую вкладывать id клиента в выписываемый JWT токен и затем извлекать его. Далее получение все операции с секретами должны выполняться с учетом полученного id клиента. Таким образом сможем исключить доступ клиентов к другим секретам.

>Клиент сможет запросить секрет по имени или только зная его uuid?

В текущей реализации предполагается, что клиент сначала спрашивает список секретов, берет из него id и далее получает по id секрет. Возможность брать секрет по имени добавить можно, но пока выглядит так, что в первом приближении id достаточно.

2023-05-07 16:53 UTC, alkurbatov commented on internal/keeper/app/app.go
> +		log.Fatal().Err(err).Msg("app - Run - postgres.New")
Поправил.

2023-05-07 16:53 UTC, alkurbatov commented on internal/keeper/app/app.go
> +		log.Fatal().Err(err).Msg("app - Run - logger.New")
Поправил.

2023-05-10 17:07 UTC, kilchik commented on internal/keepctl/repo/users_keeper.go
> +package repo
Т е там будет храниться исключительно username и какой-то ключ шифрования этого клиента? А то название как будто говорит о том, что мы там будет хранить данные несколько юзеров :)

2023-05-10 17:11 UTC, kilchik reviewed
> Здесь я планирую вкладывать id клиента в выписываемый JWT токен и затем извлекать его. Далее получение все операции с секретами должны выполняться с учетом полученного id клиента (фильтр по таблице с секретами по user_id). Таким образом сможем исключить доступ клиентов к другим секретам.

Тут я больше про то, что сможет ли один пользователь иметь несколько клиентов для управления своими кредами с такой схемой шифрования. Если установит клиентское приложение на другое устройство, сможет ли получить доступ к своим кредам?

2023-05-10 17:21 UTC, alkurbatov commented
>Тут я больше про то, что сможет ли один пользователь иметь несколько клиентов для управления своими кредами с такой схемой шифрования. Если установит клиентское приложение на другое устройство, сможет ли получить доступ к своим кредам?

Сможет, см. описание как изготавливается ключ и вот тут есть рабочая реализация https://github.com/alkurbatov/goph-keeper/blob/iter2/internal/keepctl/entity/key.go.
Если более подробно: мы берем логин и пароль и из них собираем уже ключ. Тк пара логин и пароль у нас устойчивая (те не зависит от платформы клиента) мы всегда будем поулчать один и тот же ключ для дешифровки данных.

2023-05-10 17:26 UTC, alkurbatov commented on internal/keepctl/repo/users_keeper.go
> +package repo
Да примерно так.
Так как мы вынуждены сделать аутентификцию, в таблице (репозитории) с пользователями будет хранится имя и аналог пароля (в нашем случае ключа), от которого будет взят хэш. Зарегистрированных пользователей может быть больше одного, но клиент работает только с тем, логин и пароль которого указаны на входе.

Название выбрано с точки зрения соответствия протоколу, тк тут получается двоякая ситуация: с одной стороны клиент управляет только собой (регистрируется, потенциально меняет пароль или удаляется), с другой у нас есть серверное апи, которое может быть шире (не в текущей реализации конечно). Тут я пытался сохранить некий стиль наименований и оставить пространство для маневра.

2023-05-11 08:29 UTC, alkurbatov commented
Я предлагаю этот реквест смерджить и дальше продолжить обсуждение в следующем с реализацией дизайна, заложенного в этом реквесте.

2023-05-12 18:19 UTC, merged